// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Warenwritschaftssystem_der_Segitztherme.Data;

#nullable disable

namespace Warenwritschaftssystem_der_Segitztherme.Migrations
{
    [DbContext(typeof(WarenwirtschaftContext))]
    partial class WarenwirtschaftContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.22");

            modelBuilder.Entity("Warenwritschaftssystem_der_Segitztherme.Models.Artikel", b =>
                {
                    b.Property<int>("ArtikelID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArtikelBeschreibung")
                        .HasColumnType("TEXT");

                    b.Property<float>("ArtikelGewicht")
                        .HasColumnType("REAL");

                    b.Property<float>("ArtikelMaße")
                        .HasColumnType("REAL");

                    b.Property<string>("ArtikelName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ErstelltAm")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ErstelltVon")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("GeaendertAm")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LagerID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GeaendertVon")
                        .HasColumnType("INTEGER");

                    b.HasKey("ArtikelID");

                    b.HasIndex("LagerID");

                    b.HasIndex("ErstelltVon");

                    b.HasIndex("GeaendertVon");

                    b.ToTable("Artikels");
                });

            modelBuilder.Entity("Warenwritschaftssystem_der_Segitztherme.Models.HU", b =>
                {
                    b.Property<int>("HuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnzahlArtikel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArtikelID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ErstelltAm")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ErstelltVon")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("GeaendertAm")
                        .HasColumnType("TEXT");

                    b.Property<int?>("GeaendertVon")
                        .HasColumnType("INTEGER");

                    b.Property<float>("GewichtHu")
                        .HasColumnType("REAL");

                    b.Property<int>("LagerID")
                        .HasColumnType("INTEGER");

                    b.HasKey("HuId");

                    b.HasIndex("ArtikelID");

                    b.HasIndex("ErstelltVon");

                    b.HasIndex("GeaendertVon");

                    b.HasIndex("LagerID");

                    b.ToTable("HUs");
                });

            modelBuilder.Entity("Warenwritschaftssystem_der_Segitztherme.Models.Lager", b =>
                {
                    b.Property<int>("LagerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Beschreibung")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ErstelltAm")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ErstelltVon")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("GeaendertAm")
                        .HasColumnType("TEXT");

                    b.Property<int?>("GeaendertVon")
                        .HasColumnType("INTEGER");

                    b.HasKey("LagerID");

                    b.HasIndex("ErstelltVon");

                    b.HasIndex("GeaendertVon");

                    b.ToTable("Lager");
                });

            modelBuilder.Entity("Warenwritschaftssystem_der_Segitztherme.Models.Lagerplatz", b =>
                {
                    b.Property<int>("LagerPlatzID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ErstelltAm")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ErstelltVon")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("GeaendertAm")
                        .HasColumnType("TEXT");

                    b.Property<int?>("GeaendertVon")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HUAnzahl")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LagerBereich")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LagerID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LagerPlatzName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LagerTyp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("MaxGewicht")
                        .HasColumnType("REAL");

                    b.HasKey("LagerPlatzID");

                    b.HasIndex("ErstelltVon");

                    b.HasIndex("GeaendertVon");

                    b.HasIndex("LagerID");

                    b.ToTable("Lagerplaetze");
                });

            modelBuilder.Entity("Warenwritschaftssystem_der_Segitztherme.Models.Mitarbeiter", b =>
                {
                    b.Property<int>("MitarbeiterID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ErstelltAm")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IstAktiv")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nachname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefon")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Vorname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("MitarbeiterID");

                    b.ToTable("Mitarbeiter");

                    b.HasData(
                        new
                        {
                            MitarbeiterID = 1,
                            Email = "f.schulz@example.com",
                            ErstelltAm = new DateTime(2025, 12, 18, 9, 25, 30, 490, DateTimeKind.Local).AddTicks(8332),
                            IstAktiv = true,
                            Nachname = "Schulz",
                            Telefon = "0123456789",
                            Vorname = "Frankich"
                        },
                        new
                        {
                            MitarbeiterID = 2,
                            Email = "admin@system.com",
                            ErstelltAm = new DateTime(2025, 12, 18, 9, 25, 30, 490, DateTimeKind.Local).AddTicks(8337),
                            IstAktiv = true,
                            Nachname = "Admin",
                            Vorname = "System"
                        });
                });

            modelBuilder.Entity("Warenwritschaftssystem_der_Segitztherme.Models.Artikel", b =>
                {
                    b.HasOne("Warenwritschaftssystem_der_Segitztherme.Models.Mitarbeiter", "ErstelltVonMitarbeiter")
                        .WithMany()
                        .HasForeignKey("ErstelltVon")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Warenwritschaftssystem_der_Segitztherme.Models.Mitarbeiter", "GeaendertVonMitarbeiter")
                        .WithMany()
                        .HasForeignKey("GeaendertVon")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ErstelltVonMitarbeiter");

                    b.Navigation("GeaendertVonMitarbeiter");
                });

            modelBuilder.Entity("Warenwritschaftssystem_der_Segitztherme.Models.HU", b =>
                {
                    b.HasOne("Warenwritschaftssystem_der_Segitztherme.Models.Artikel", null)
                        .WithMany()
                        .HasForeignKey("ArtikelID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Warenwritschaftssystem_der_Segitztherme.Models.Mitarbeiter", "ErstelltVonMitarbeiter")
                        .WithMany()
                        .HasForeignKey("ErstelltVon")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Warenwritschaftssystem_der_Segitztherme.Models.Mitarbeiter", "GeaendertVonMitarbeiter")
                        .WithMany()
                        .HasForeignKey("GeaendertVon")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Warenwritschaftssystem_der_Segitztherme.Models.Lager", null)
                        .WithMany()
                        .HasForeignKey("LagerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ErstelltVonMitarbeiter");

                    b.Navigation("GeaendertVonMitarbeiter");
                });

            modelBuilder.Entity("Warenwritschaftssystem_der_Segitztherme.Models.Lager", b =>
                {
                    b.HasOne("Warenwritschaftssystem_der_Segitztherme.Models.Mitarbeiter", "ErstelltVonMitarbeiter")
                        .WithMany()
                        .HasForeignKey("ErstelltVon")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Warenwritschaftssystem_der_Segitztherme.Models.Mitarbeiter", "GeaendertVonMitarbeiter")
                        .WithMany()
                        .HasForeignKey("GeaendertVon")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ErstelltVonMitarbeiter");

                    b.Navigation("GeaendertVonMitarbeiter");
                });

            modelBuilder.Entity("Warenwritschaftssystem_der_Segitztherme.Models.Lagerplatz", b =>
                {
                    b.HasOne("Warenwritschaftssystem_der_Segitztherme.Models.Mitarbeiter", "ErstelltVonMitarbeiter")
                        .WithMany()
                        .HasForeignKey("ErstelltVon")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Warenwritschaftssystem_der_Segitztherme.Models.Mitarbeiter", "GeaendertVonMitarbeiter")
                        .WithMany()
                        .HasForeignKey("GeaendertVon")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Warenwritschaftssystem_der_Segitztherme.Models.Lager", null)
                        .WithMany()
                        .HasForeignKey("LagerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ErstelltVonMitarbeiter");

                    b.Navigation("GeaendertVonMitarbeiter");
                });

            modelBuilder.Entity("Warenwritschaftssystem_der_Segitztherme.Models.Lager", b =>
                {
                    b.Navigation("Artikel");
                });
#pragma warning restore 612, 618
        }
    }
}
