// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Warenwritschaftssystem_der_Segitztherme.Data;

#nullable disable

namespace Warenwritschaftssystem_der_Segitztherme.Migrations
{
    [DbContext(typeof(WarenwirtschaftContext))]
    partial class WarenwirtschaftContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.22");

            modelBuilder.Entity("Warenwritschaftssystem_der_Segitztherme.Models.Artikel", b =>
                {
                    b.Property<int>("ArtikelID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArtikelBeschreibung")
                        .HasColumnType("TEXT");

                    b.Property<float>("ArtikelGewicht")
                        .HasColumnType("REAL");

                    b.Property<float>("ArtikelMaße")
                        .HasColumnType("REAL");

                    b.Property<string>("ArtikelName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("LagerID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ArtikelID");

                    b.HasIndex("LagerID");

                    b.ToTable("Artikels");
                });

            modelBuilder.Entity("Warenwritschaftssystem_der_Segitztherme.Models.HU", b =>
                {
                    b.Property<int>("HuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnzahlArtikel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArtikelID")
                        .HasColumnType("INTEGER");

                    b.Property<float>("GewichtHu")
                        .HasColumnType("REAL");

                    b.Property<int>("LagerID")
                        .HasColumnType("INTEGER");

                    b.HasKey("HuId");

                    b.HasIndex("ArtikelID");

                    b.HasIndex("LagerID");

                    b.ToTable("HUs");
                });

            modelBuilder.Entity("Warenwritschaftssystem_der_Segitztherme.Models.Lager", b =>
                {
                    b.Property<int>("LagerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Beschreibung")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LagerID");

                    b.ToTable("Lager");
                });

            modelBuilder.Entity("Warenwritschaftssystem_der_Segitztherme.Models.Lagerplatz", b =>
                {
                    b.Property<int>("LagerPlatzID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("HUAnzahl")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LagerBereich")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LagerID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LagerPlatzName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LagerTyp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("MaxGewicht")
                        .HasColumnType("REAL");

                    b.HasKey("LagerPlatzID");

                    b.HasIndex("LagerID");

                    b.ToTable("Lagerplaetze");
                });

            modelBuilder.Entity("Warenwritschaftssystem_der_Segitztherme.Models.Artikel", b =>
                {
                    b.HasOne("Warenwritschaftssystem_der_Segitztherme.Models.Lager", "Lager")
                        .WithMany("Artikel")
                        .HasForeignKey("LagerID");

                    b.Navigation("Lager");
                });

            modelBuilder.Entity("Warenwritschaftssystem_der_Segitztherme.Models.HU", b =>
                {
                    b.HasOne("Warenwritschaftssystem_der_Segitztherme.Models.Artikel", null)
                        .WithMany()
                        .HasForeignKey("ArtikelID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Warenwritschaftssystem_der_Segitztherme.Models.Lager", null)
                        .WithMany()
                        .HasForeignKey("LagerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Warenwritschaftssystem_der_Segitztherme.Models.Lagerplatz", b =>
                {
                    b.HasOne("Warenwritschaftssystem_der_Segitztherme.Models.Lager", null)
                        .WithMany()
                        .HasForeignKey("LagerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Warenwritschaftssystem_der_Segitztherme.Models.Lager", b =>
                {
                    b.Navigation("Artikel");
                });
#pragma warning restore 612, 618
        }
    }
}
